{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stormforge-agent.fullname" . }}
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    {{- include "stormforge-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
- apiGroups:
  - optimize.stormforge.io
  resources:
  - workloadoptimizers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - optimize.stormforge.io
  resources:
  - workloadoptimizers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- if or .Values.openshift }}
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  verbs:
    - use
  resourceNames:
    - anyuid
{{- end }}
{{ if .Values.rbac.additional }}
{{ .Values.rbac.additional  }}
{{- end}}
{{- if not .Values.rbac.useViewRole }}
# Minimum RBAC for Built-in Resources
- apiGroups:
    - ""
  resources:
    - pods
    - replicationcontrollers
    - replicationcontrollers/scale
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - replicasets
    - replicasets/scale
    - statefulsets
    - statefulsets/scale
    - daemonsets
    - deployments
    - deployments/scale
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - monitoring.coreos.com
  resources:
    - prometheuses
  verbs:
    - get
    - list
    - watch
{{- end}}
{{ end }}
