{{- $scopeForRecycleFn := include "stormforge-agent.scopeForRecycleFn" . | fromJson -}}
{{- $secret := $scopeForRecycleFn.secret -}}
{{- $values := dict
  "STORMFORGE_CLIENT_ID" (include "stormforge-agent.recycle.clientID" $scopeForRecycleFn)
  "STORMFORGE_CLIENT_SECRET" (include "stormforge-agent.recycle.clientSecret" $scopeForRecycleFn)
  "STORMFORGE_ISSUER" (include "stormforge-agent.recycle.issuer" $scopeForRecycleFn)
  "STORMFORGE_SERVER" (include "stormforge-agent.recycle.address" $scopeForRecycleFn)
  "STORMFORGE_CLUSTER_NAME" (include "stormforge-agent.recycle.clusterName" $scopeForRecycleFn)
-}}

{{- if .Values.proxyUrl -}}
  {{- $_ := set $values "HTTPS_PROXY" .Values.proxyUrl -}}
{{- end -}}
{{- if .Values.noProxy -}}
  {{- $_ := set $values "NO_PROXY" .Values.noProxy -}}
{{- end -}}

{{- range .Values.extraEnvVars -}}{{- $_ := set $values .name .value -}}{{- end -}}

{{- range $k, $v := $values -}}{{- $_ := set $values $k ($v | b64enc) -}}{{- end -}}
{{- range $k, $v := $secret -}}{{- $_ := set $secret $k ($v | b64enc) -}}{{- end -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "stormforge-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stormforge-agent.labels" . | nindent 4 }}

data:
  {{- merge $values $secret | toYaml | nindent 2 }}
