apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "optimize-live.fullname" . }}
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
  namespace: {{ include "optimize-live.namespace" . }}
data:
  live-config.yaml: |
    # see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1#ControllerManagerConfigurationSpec
    apiVersion: optimize.stormforge.io/v1
    kind: LiveConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: false
      resourceName: 84daec31.optimize.stormforge.io

    # Component settings
    components:
      tsdb:
        image: "{{ .Values.tsdb.image.repository }}:{{ .Values.tsdb.image.tag }}"
        imagePullPolicy: {{ .Values.tsdb.image.pullPolicy }}
        {{- if .Values.tsdb.resources }}
        resources:
          {{- toYaml .Values.tsdb.resources | nindent 10 }}
        {{- end }}
      applier:
        image: "{{ .Values.applier.image.repository }}:{{ .Values.applier.image.tag }}"
        imagePullPolicy: {{ .Values.applier.image.pullPolicy }}
        {{- if .Values.applier.resources }}
        resources:
          {{- toYaml .Values.applier.resources | nindent 10 }}
        {{- end }}
      recommender:
        image: "{{ .Values.recommender.image.repository }}:{{ .Values.recommender.image.tag }}"
        imagePullPolicy: {{ .Values.recommender.image.pullPolicy }}
        {{- if .Values.recommender.resources }}
        resources:
          {{- toYaml .Values.recommender.resources | nindent 10 }}
        {{- end }}
      grafana:
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
        {{- if .Values.grafana.resources }}
        resources:
          {{- toYaml .Values.grafana.resources | nindent 10 }}
        {{- end }}
