apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "optimize-live.fullname" . }}
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
  namespace: {{ include "optimize-live.namespace" . }}
data:
  live-config.yaml: |
    # see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/config/v1alpha1#ControllerManagerConfigurationSpec
    apiVersion: optimize.stormforge.io/v1
    kind: LiveConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: false
      resourceName: 84daec31.optimize.stormforge.io

    # Component settings
    components:
      {{- if .Values.component.resources.tsdb }}
      tsdb:
        resources:
          {{- toYaml .Values.component.resources.tsdb | nindent 10 }}
      {{- end }}
      {{- if .Values.component.resources.applier }}
      applier:
        resources:
          {{- toYaml .Values.component.resources.applier | nindent 10 }}
      {{- end }}
      {{- if .Values.component.resources.recommender }}
      recommender:
        resources:
          {{- toYaml .Values.component.resources.recommender | nindent 10 }}
      {{- end }}
      {{- if .Values.component.resources.grafana }}
      grafana:
        resources:
          {{- toYaml .Values.component.resources.grafana | nindent 10 }}
      {{- end }}
