---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "optimize-live.clusterRoleBindingName" . }}
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "optimize-live.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "optimize-live.serviceAccountName" . }}
  namespace: {{ include "optimize-live.namespace" . }}

{{ if .Values.rbac.additional }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "optimize-live.clusterRoleBindingName" . }}-additional
  labels:
    {{- include "optimize-live.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "optimize-live.clusterRoleName" . }}-additional
subjects:
- kind: ServiceAccount
  name: {{ include "optimize-live.serviceAccountName" . }}
  namespace: {{ include "optimize-live.namespace" . }}
{{ end }}
