apiVersion: v2
name: optimize-controller
version: 2.1.7
description: Kubernetes Performance Testing and resource optimization for flawless app performance and cloud efficiency without manual tuning.
type: application
home: https://www.stormforge.io/
sources:
- https://github.com/thestormforge/optimize-controller
- https://github.com/thestormforge/helm-charts
icon: https://app.stormforge.io/img/logo.png
appVersion: 2.1.7
kubeVersion: 1.14.x-0 - 1.21.x-0
