apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.name" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  namespace: {{ include "optimize-live.namespace" . }}
spec:
  selector:
    component: grafana
  ports:
    - name: http
      port: {{ include "grafana.servicePort" . }}
      protocol: TCP
      targetPort: {{ include "grafana.serviceTargetPort" . }}
  type: ClusterIP